### ISSUE TITLE
Researches on line follower sensors 

### ISSUE THREAD

**Issue by NadaEssamAhmed** [NadaEssamAhmed/ASUMobiCarG02#3]
In this phase we will add a line tracking sensor to our Rc car which makes it move by tracking lines 
So in this issue we will go more deeply  to know more about this sensor

**Comment by HalaSafwat** [comment]
[3way_line_tracker_sensor_tutorial.pdf](https://github.com/NadaEssamAhmed/ASUMobiCarG02/files/1853504/3way_line_tracker_sensor_tutorial.pdf)

**Comment by NadaIhabAhmed** [comment]
[Line Follower sensors report.pdf](https://github.com/NadaEssamAhmed/ASUMobiCarG02/files/1853547/Line.Follower.sensors.report.pdf)

**Comment by NadaEssamAhmed** [comment]
[REPORT ON  LINE.docx](https://github.com/NadaEssamAhmed/ASUMobiCarG02/files/1853587/REPORT.ON.LINE.docx)

**Comment by NadaEssamAhmed** [comment]
![image](https://user-images.githubusercontent.com/36282357/37992009-eab32a16-320a-11e8-8b7f-07112b9e08c5.png)
Connection diagram
